<?php

declare(strict_types=1);

namespace RomainMillan\WebPushNotification\Domain\Subscription;

use RomainMillan\WebPushNotification\Domain\Exception\InvalidValue;

/**
 * 32 lowercase hex characters (128 random bits).
 *
 * Generated by the core (SubscriptionIdGenerator) rather than by the database, so an
 * aggregate has its identity before it is persisted and events can carry it.
 */
final readonly class SubscriptionId
{
    private function __construct(
        private string $value,
    ) {
    }

    public static function fromString(string $value): self
    {
        if (1 !== preg_match('/^[0-9a-f]{32}$/D', $value)) {
            throw InvalidValue::because('Cannot accept a subscription id that is not 32 lowercase hexadecimal characters.');
        }

        return new self($value);
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function toString(): string
    {
        return $this->value;
    }
}
