<?php

declare(strict_types=1);

use RomainMillan\WebPushNotification\Domain\Message\DeliveryOptions;
use RomainMillan\WebPushNotification\Domain\Message\Urgency;
use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

use function Symfony\Component\String\u;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->arrayNode('vapid')
                ->isRequired()
                ->children()
                    ->scalarNode('public_key')->isRequired()->cannotBeEmpty()->end()
                    ->scalarNode('private_key')->isRequired()->cannotBeEmpty()->end()
                    ->scalarNode('subject')->isRequired()->cannotBeEmpty()->info('mailto:ops@example.com or https://example.com')->end()
                ->end()
            ->end()
            ->scalarNode('origin')->defaultNull()->info('https://example.com — the application origin; default: derived from framework.router.default_uri. Validated on first use.')->end()
            ->arrayNode('subscriber')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('resolver')->defaultNull()->info('Service id implementing SubscriberIdResolver. Default: the user implements WebPushSubscriber.')->end()
                ->end()
            ->end()
            ->arrayNode('storage')
                ->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('type')->values(['doctrine', 'custom'])->defaultValue('doctrine')->end()
                    ->scalarNode('connection')->defaultValue('default')->info('Doctrine DBAL connection name')->end()
                    ->scalarNode('repository')->defaultNull()->info('custom: service implementing SubscriptionRepository, PurgeableSubscriptions and SubscriptionReadModel')->end()
                    ->scalarNode('transaction_boundary')->defaultNull()->info('custom: service implementing TransactionBoundary')->end()
                ->end()
            ->end()
            ->arrayNode('encryption')
                ->addDefaultsIfNotSet()
                ->info('Optional encryption at rest of endpoints and keys ("keyId:base64 of 32 bytes").')
                ->children()
                    ->scalarNode('current')->defaultNull()->end()
                    ->arrayNode('previous')->scalarPrototype()->end()->defaultValue([])->end()
                ->end()
            ->end()
            ->integerNode('max_subscriptions_per_subscriber')->defaultValue(16)->min(1)->end()
            ->enumNode('retirement')->values(['delete', 'deactivate'])->defaultValue('deactivate')->end()
            ->arrayNode('anonymous')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')->defaultFalse()->end()
                    ->scalarNode('rate_limiter')->defaultNull()->info('Name of a framework.rate_limiter limiter; required when enabled')->end()
                    ->integerNode('max_active')->defaultValue(10000)->min(0)->end()
                    ->scalarNode('stale_after')->defaultValue('90 days')->end()
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $anonymous): bool => true === $anonymous['enabled'] && null === $anonymous['rate_limiter'])
                    ->thenInvalid('Anonymous web push subscriptions require anonymous.rate_limiter: refusing to open an unbounded public endpoint.')
                ->end()
            ->end()
            ->arrayNode('push_services')
                ->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('extra_hosts')->scalarPrototype()->end()->defaultValue([])->info('Self-hosted push services; still subject to the public IP check')->end()
                ->end()
            ->end()
            ->arrayNode('delivery')
                ->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('dispatcher')->values(['immediate', 'messenger'])->defaultValue('immediate')->end()
                    ->integerNode('timeout')->defaultValue(15)->min(1)->end()
                    ->booleanNode('dns_pinning')->defaultTrue()->end()
                    ->integerNode('ttl')->defaultValue(DeliveryOptions::MAX_TTL)->min(0)->max(DeliveryOptions::MAX_TTL)->info('Default TTL in seconds (RFC 8030)')->end()
                    ->enumNode('urgency')->values(array_map(static fn (Urgency $urgency): string => $urgency->value, Urgency::cases()))->defaultValue(Urgency::Normal->value)->end()
                ->end()
            ->end()
            ->arrayNode('lock')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('factory')->defaultNull()->info('LockFactory service id; default: lock.factory when available, else the quota is soft')->end()
                ->end()
            ->end()
            ->arrayNode('routes')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('csrf_token_id')->defaultValue('web_push')->end()
                    ->scalarNode('csrf_header')->defaultValue('X-CSRF-Token')->end()
                    ->scalarNode('unsubscribe_rate_limiter')->defaultNull()->info('Name of a framework.rate_limiter limiter; default: web_push_unsubscribe (sliding window, 30 per minute), declared by the bundle')->end()
                ->end()
            ->end()
            ->arrayNode('service_worker')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('fallback_title')->defaultValue('Notification')->end()
                    ->scalarNode('icon')->defaultValue('')->end()
                    ->scalarNode('badge')->defaultValue('')->end()
                    ->arrayNode('click_prefixes')->scalarPrototype()->end()->defaultValue(['/'])->end()
                    ->arrayNode('asset_hosts')->scalarPrototype()->end()->defaultValue([])->end()
                    ->scalarNode('state_cache')->defaultValue('web-push-state')->end()
                    ->scalarNode('prebuilt_path')->defaultNull()->info('Defaults to the package assets/dist/web-push-sw.js')->end()
                    ->scalarNode('register_url')->defaultNull()->info('Script the page registers, e.g. your own /sw.js that calls importScripts("/web-push-sw.js"); default: the web_push_service_worker route')->end()
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $serviceWorker): bool => is_string($serviceWorker['register_url']) && (!u($serviceWorker['register_url'])->startsWith('/') || u($serviceWorker['register_url'])->startsWith('//')))
                    ->thenInvalid('Cannot register a service worker outside the application origin: service_worker.register_url must be an absolute path such as "/sw.js".')
                ->end()
            ->end()
            ->arrayNode('purge')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('retired_after')->defaultValue('30 days')->end()
                ->end()
            ->end()
        ->end();
};
